apiVersion: apps/v1
kind: Deployment
metadata:
  name: todos-fe-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todos-fe
  template:
    metadata:
      labels:
        app: todos-fe
    spec:
      volumes:
        - name: shared-log
          # emptyDir: {}
          persistentVolumeClaim: # DONE:
            claimName: ex13-claim
      containers:
        - name: todos-fe
          image: usb9/todos-fe:2.02.2
          # We use npm run build >>> this env not work >>> use 2 file.env in /fe 
          # env:
          #   - name: REACT_APP_BACKEND_URL
          #     value: http://35.184.75.254:8081/api
          #     # value: http://localhost:8081/api
          volumeMounts:
          - name: shared-log
            mountPath: /usr/src/app/files