apiVersion: apps/v1
kind: Deployment
metadata:
  name: ex2-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ex2
  template:
    metadata:
      labels:
        app: ex2
    spec:
      containers:
        - name: ex2
          image: usb9/ex2:ver2
